### ISSUE TITLE
Mangled `regen-certificates.yml` task file in firstboot

### ISSUE THREAD

**Issue by viccross** [viccross/ansible-playbooks#151]
When running `ipconf.sh`, the certificate regeneration step fails:
```
ERROR! We were unable to read either as JSON nor YAML, there are the e
JSON: Expecting value: line 1 column 1 (char 0)
Syntax error while loading YAML.
  mapping values are not allowed in this context
The error appears to be in '/opt/ansible/regen-certificates.yml': line
be elsewhere in the file depending on the exact syntax problem.
The offending line appears to be:
    shell:
      cmd: curl -v -T {'src': 'regen-certificates.yml.j2'. 'dest': '/o
                            ^ here
```
(partial output due to screen-shotting someones share of an Integrated 3270 Console window)

Looking at the source, there is an un-escaped Jinja2 tag introduced in e9e40bd that introduced the bug:
```
  - name: copy the PKCS#12 files to z/VM # noqa command-instead-of-module command-instead-of-shell no-changed-when
    shell:
      cmd: curl -v -T {{ item }}.p12 -Q "CWD /../VMBFS:VMSYS:GSKSSLDB/" ftp://GSKADMIN.BY.{{ smapi_user }}:{{ smapi_password }}@{{ zvm_internal_ip_address }}/
      chdir: /etc/pki/tls/certs
    with_items:
    - zVM
    - zVMLDAP
```
The intention was that the `with_items` list be passed into the command line at `{{ item }}`, but this tag should be escaped because we want it to be expanded at runtime on the end-ELAN not at deploy-time on the build-ELAN.
