### ISSUE TITLE
How to add worker nodes to an ESI OCP cluster

### ISSUE THREAD

**Issue by viccross** [viccross/ansible-playbooks#66]
In discussion with Deloitte, I did an on-the-fly whip-together of a process to create new guests for OCP. At a high level it goes like this:
- ensure sufficient disk space present in the DirMaint `LINUXEAV` group
- copy the "workers" section of the `group_vars\all.yml` file into a new dictionary called "new-workers", bringing with it however many worker definitions you need (or just take the first one)
- update (and duplicate if needed) the entries under "new-workers" with details of the guest(s) to be added
- create a new playbook `create-new-workers.yml` with content like this:
```
---
- name: create ocp4 worker guests
  hosts: s390x_bastion_workstation
  tasks:
  - name: create the worker nodes
    include_tasks: tasks/create-guest.yml
    vars:
      coreos_role: new-workers
      directory_entry: "{{ lookup('template', '{{ playbook_dir }}/roles/create-cluster/templates/guest.direct.j2') }}"
    with_items: "{{ cluster_nodes[coreos_role] }}"
```
- Move the dictionaries from under the `new-workers` item to under the `workers` item
- Edit `ocp-dasd.sh`, look for the line that contains the OCP guests and add the new guest names to the variable
- `systemctl start ocp-dasd.service`
- update the certificate in the `worker.ign`?
- create the new ZNETBOOT files (expand this?)
- log on the new guests
- verify they join the cluster

We can automate some or all of this.
